version: '3.8'

services: 
  web:
    container_name: cocktailwiki
    image: cocktailwiki:0.0.8
    build: 
      context: .
    ports:
      - "5000:5000"
    environment: 
      - EXTERNAL_PORT=5000
      - PGDATABASE=cocktailwikidb
      - PGUSER=postgres
      - DATABASE_PASSWORD=hd.214375
      - PGHOST=db
    depends_on: 
      - db
  db: 
    container_name: db
    image: "postgres:14"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hd.214375
      - POSTGRES_DB=cocktailwikidb
    volumes:
      - nps_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/

volumes:
  nps_data: {}